// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWeb;

#nullable disable

namespace DigitalMenu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240719175837_entidades")]
    partial class entidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DigitalMenu.Models.Entity.Dishe", b =>
                {
                    b.Property<int>("IdDishes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("DishescategoryIdDishesCategory")
                        .HasColumnType("int");

                    b.Property<int>("IdDishesCategory")
                        .HasColumnType("int");

                    b.Property<int>("IdRestaurant")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegisterUser")
                        .HasColumnType("longtext");

                    b.Property<int?>("RestaurantIdRestaurant")
                        .HasColumnType("int");

                    b.HasKey("IdDishes");

                    b.HasIndex("DishescategoryIdDishesCategory");

                    b.HasIndex("RestaurantIdRestaurant");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("DigitalMenu.Models.Entity.DisheCategory", b =>
                {
                    b.Property<int>("IdDishesCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegisterUser")
                        .HasColumnType("longtext");

                    b.HasKey("IdDishesCategory");

                    b.ToTable("Dishescategory");
                });

            modelBuilder.Entity("DigitalMenu.Models.Entity.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Document")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("EmployeedetailsIdEmployee")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegisterUser")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdEmployee");

                    b.HasIndex("EmployeedetailsIdEmployee");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DigitalMenu.Models.Entity.EmployeeDetails", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdEmployee");

                    b.ToTable("Employeedetails");
                });

            modelBuilder.Entity("DigitalMenu.Models.Entity.Restaurant", b =>
                {
                    b.Property<int>("IdRestaurant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegisterUser")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("RestaurantdetailsIdRestaurant")
                        .HasColumnType("int");

                    b.HasKey("IdRestaurant");

                    b.HasIndex("RestaurantdetailsIdRestaurant");

                    b.ToTable("Restaurant");
                });

            modelBuilder.Entity("DigitalMenu.Models.Entity.RestaurantDetails", b =>
                {
                    b.Property<int>("IdRestaurant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TaxId")
                        .HasColumnType("longtext");

                    b.HasKey("IdRestaurant");

                    b.ToTable("Restaurantdetails");
                });

            modelBuilder.Entity("DigitalMenu.Models.Entity.RestaurantEmployee", b =>
                {
                    b.Property<int>("IdRestaurantEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<int>("IdRestaurant")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastUpdateUser")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegisterUser")
                        .HasColumnType("longtext");

                    b.Property<int?>("RestaurantIdRestaurant")
                        .HasColumnType("int");

                    b.HasKey("IdRestaurantEmployee");

                    b.HasIndex("RestaurantIdRestaurant");

                    b.ToTable("Restaurantemployee");
                });

            modelBuilder.Entity("DigitalMenu.Models.Entity.Dishe", b =>
                {
                    b.HasOne("DigitalMenu.Models.Entity.DisheCategory", "Dishescategory")
                        .WithMany("Dishes")
                        .HasForeignKey("DishescategoryIdDishesCategory");

                    b.HasOne("DigitalMenu.Models.Entity.Restaurant", "Restaurant")
                        .WithMany("Dishes")
                        .HasForeignKey("RestaurantIdRestaurant");

                    b.Navigation("Dishescategory");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("DigitalMenu.Models.Entity.Employee", b =>
                {
                    b.HasOne("DigitalMenu.Models.Entity.EmployeeDetails", "Employeedetails")
                        .WithMany()
                        .HasForeignKey("EmployeedetailsIdEmployee");

                    b.Navigation("Employeedetails");
                });

            modelBuilder.Entity("DigitalMenu.Models.Entity.Restaurant", b =>
                {
                    b.HasOne("DigitalMenu.Models.Entity.RestaurantDetails", "Restaurantdetails")
                        .WithMany()
                        .HasForeignKey("RestaurantdetailsIdRestaurant");

                    b.Navigation("Restaurantdetails");
                });

            modelBuilder.Entity("DigitalMenu.Models.Entity.RestaurantEmployee", b =>
                {
                    b.HasOne("DigitalMenu.Models.Entity.Restaurant", "Restaurant")
                        .WithMany("Restaurantemployee")
                        .HasForeignKey("RestaurantIdRestaurant");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("DigitalMenu.Models.Entity.DisheCategory", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("DigitalMenu.Models.Entity.Restaurant", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("Restaurantemployee");
                });
#pragma warning restore 612, 618
        }
    }
}
